[workspace]
resolver = "2"
members = ["bin/*", "lib/*", "client/core/rs", "client/periphery/rs"]

[workspace.package]
version = "1.7.3"
edition = "2021"
authors = ["mbecker20 <becker.maxh@gmail.com>"]
license = "GPL-3.0-or-later"
repository = "https://github.com/mbecker20/monitor"
homepage = "https://docs.monitor.mogh.tech"

[patch.crates-io]
monitor_client = { path = "client/core/rs" }

[workspace.dependencies]
# LOCAL
monitor_client = "1.7.3"
periphery_client = { path = "client/periphery/rs" }
command = { path = "lib/command" }
logger = { path = "lib/logger" }
git = { path = "lib/git" }

# MOGH
run_command = { version = "0.0.6", features = ["async_tokio"] }
serror = { version = "0.4.3", default-features = false }
slack = { version = "0.1.0", package = "slack_client_rs" }
derive_default_builder = "0.1.8"
derive_empty_traits = "0.1.0"
merge_config_files = "0.1.5"
termination_signal = "0.1.3"
async_timing_util = "0.1.14"
partial_derive2 = "0.4.3"
derive_variants = "1.0.0"
mongo_indexed = "0.3.0"
resolver_api = "1.1.0"
toml_pretty = "1.1.2"
parse_csl = "0.1.0"
mungos = "0.5.6"
svi = "1.0.1"

# ASYNC
tokio = { version = "1.38.0", features = ["full"] }
reqwest = { version = "0.12.4", features = ["json"] }
tokio-util = "0.7.11"
futures = "0.3.30"
futures-util = "0.3.30"

# SERVER
axum = { version = "0.7.5", features = ["ws", "json"] }
axum-extra = { version = "0.9.3", features = ["typed-header"] }
tower = { version = "0.4.13", features = ["timeout"] }
tower-http = { version = "0.5.2", features = ["fs", "cors"] }
tokio-tungstenite = "0.23.0"

# SER/DE
ordered_hash_map = { version = "0.4.0", features = ["serde"] }
serde = { version = "1.0.203", features = ["derive"] }
strum = { version = "0.26.2", features = ["derive"] }
serde_json = "1.0.117"
toml = "0.8.13"

# ERROR
anyhow = "1.0.86"
thiserror = "1.0.61"

# LOGGING
opentelemetry_sdk = { version = "0.23.0", features = ["rt-tokio"] }
tracing-subscriber = { version = "0.3.18", features = ["json"] }
tracing-opentelemetry = "0.24.0"
opentelemetry-otlp = "0.16.0"
opentelemetry = "0.23.0"
tracing = "0.1.40"

# CONFIG
clap = { version = "4.5.4", features = ["derive"] }
dotenv = "0.15.0"
envy = "0.4.2"

# CRYPTO
uuid = { version = "1.8.0", features = ["v4", "fast-rng", "serde"] }
urlencoding = "2.1.3"
bcrypt = "0.15.1"
base64 = "0.22.1"
hmac = "0.12.1"
sha2 = "0.10.8"
rand = "0.8.5"
jwt = "0.16.0"
hex = "0.4.3"

# SYSTEM
bollard = "0.16.1"
sysinfo = "0.30.12"

# CLOUD
aws-config = "1.5.0"
aws-sdk-ec2 = "1.46.0"

# MISC
derive_builder = "0.20.0"
typeshare = "1.0.3"
colored = "2.1.0"
bson = "2.10.0"
