[package]
name = "migrator"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
monitor_client.workspace = true
logger.workspace = true
#
mungos.workspace = true
#
tokio.workspace = true
anyhow.workspace = true
dotenv.workspace = true
envy.workspace = true
serde.workspace = true
tracing.workspace = true
chrono = "0.4"